spring:
  application:
    name: popularity-score


server:
  port: 8080

logging:
  level:
    root: INFO
    me.mohamed.redcare.popularityscore: TRACE

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"


springdoc:
  swagger-ui:
    path: /swagger
    operationsSorter: method
  api-docs:
    path: /api-docs


resilience4j.circuitbreaker:
  instances:
    githubClient:
      failureRateThreshold: 50
      slidingWindowSize: 10
      waitDurationInOpenState: 30s

github:
  base-url: "https://api.github.com"
